name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.1'
        bundler-cache: true
    - name: Run
      run: bundle exec rake rubocop

  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby: [2.7, 3.0, 3.1]
        rails: [5, 6, 7]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
      env:
        RAILS_VERSION: ${{ matrix.rails }}
        BUNDLE_FROZEN: false
    - name: Run tests
      run: bundle exec rake test
