name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run
      run: bundle exec rake rubocop

  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, '3.0', 3.1] # Concerning quotes see: https://github.com/actions/runner/issues/849
        rails: [6, 7]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install gems
      env:
        RAILS_VERSION: ${{ matrix.rails }}
      run: |
        export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/rails_${RAILS_VERSION}.gemfile"
        bundle install --jobs 4 --retry 3

    - if: matrix.ruby == 3.1 && matrix.rails == 7
      name: Setup Code Climate test-reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Run tests
      run: bundle exec rake test

    - if: matrix.ruby == 3.1 && matrix.rails == 7
      name: Publish code coverage
      run: |
        export GIT_BRANCH=$GITHUB_HEAD_REF
        echo GIT_BRANCH: $GIT_BRANCH
        ./cc-test-reporter after-build
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}